import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/globals.css";
import { FlexLayout } from "@/components/FlexLayout";
import { Footer } from "@/components/commons/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <FlexLayout styleClassNames="m-auto max-w-[1240px] justify-center px-[10px] lg:px-0">
          {children}
          <Footer />
        </FlexLayout>
      </body>
    </html>
  );
}
